### ISSUE TITLE
ReactNative-0.38,a warning,'useNativeDriver' is not supported

### ISSUE THREAD

**Issue by TuomaXu** [exponentjs/ex-navigation#276]
I updata the last react-native@0.38 
run app in iphone 7 plus simulator,it put a warning.

the message : 

Animated: 'useNativeDriver' is not supported because the native animation module is missing.
Falling back to JS-based animation.
To resolve this , add 'RCTAnimation' module to this app,or remove 'useNativeDriver'

**Comment by sibelius** [comment]
U need to link RCTAnimation in ur Xcode project, search it inside react-native folder inside node_modules

**Comment by apaajabolehd** [comment]
same problem here. I already link RCTAnimation to the project, but the warning is still there. I use this reference to link the RCTAnimation
http://stackoverflow.com/questions/29311326/how-to-create-a-simple-animation-effect

Is there anything wrong?

**Comment by flizzer** [comment]
I added the RCTAnimation project to my libraries in Xcode 8.1, but I'm still getting the above message.  I'm a noob to linking with Xcode.  Is there something else I need to do?  Thanks.

**Comment by apaajabolehd** [comment]
@flizzer you're welcome, glad can help. I fixed the problem. Just open the xcode project, clean and rebuild, then rerun `react-native run-ios`. Hope it helps you.

**Comment by flizzer** [comment]
@apaajabolehd I tried cleaning and rebuilding, but I still get the warning in the simulator.  I have the RCTAnimation.xcodeproj project under my "Libraries" folder and I have libRCTAnimation.a under the "Products" folder and under "Link Binary With Libraries" in "Build Phases".  Is there a step I've overlooked maybe?  Thanks.

**Comment by alexbelyeu** [comment]
Same problem here @flizzer. I wonder what we're overlooking.

**Comment by MarlBurroW** [comment]
Same issue here

**Comment by henrikra** [comment]
I commented on react-native repo how to fix this issue :) https://github.com/facebook/react-native/issues/11094#issuecomment-263240420

**Comment by flizzer** [comment]
Thanks @henrikra!  I thought I had done that, but being a noob at linking in Xcode, I hadn't done it quite right.  Once I figured out how to add the .a file to the correct project.  It worked like a charm.  Thanks again!

**Comment by futurechallenger** [comment]
@henrikra 's way works.
@flizzer you have to clean the project and re-run it.

**Comment by sibelius** [comment]
@TuomaXu can we close this?
