### ISSUE TITLE
Android: Too much empty space in top of navigationbar 

### ISSUE THREAD

**Issue by tpedersen123** [exponentjs/ex-navigation#49]
When using the component without application bar, the `ExNavigationBar`contains extra top margin. The navigation bar should be as close to the status bar as possible. 

This margin is determined by the `STATUSBAR_HEIGHT`in `ExNavigationBar.js` 
Setting this value to 0 fixes the issue. 

@brentvatne

**Comment by brentvatne** [comment]
Fixed in ba31404

**Comment by coderbyheart** [comment]
I still have this problem with `master`:

![screenshot_20161006-130146](https://cloud.githubusercontent.com/assets/188915/19150047/3356b424-8bc5-11e6-9b55-4ffc8dd077e6.png)

**Comment by coderbyheart** [comment]
Actually, I have the problem, when I use it in another project. `master` is fine.
